name: plantmae
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2024.3.11=h06a4308_0
  - cudatoolkit=11.1.1=hb139c0e_13
  - einops=0.8.0=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - giflib=5.2.2=hd590300_0
  - gmp=6.3.0=h59595ed_1
  - gnutls=3.6.13=h85f3911_1
  - icu=73.2=h59595ed_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jpeg=9b=h024ee3a_2
  - lame=3.100=h166bdaf_1003
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libcblas=3.9.0=5_h92ddd45_netlib
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libgomp=13.2.0=h807b86a_5
  - libhwloc=2.9.1=hd6dc26d_0
  - libiconv=1.17=hd590300_2
  - liblapack=3.9.0=5_h92ddd45_netlib
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libtiff=4.2.0=h85742a9_0
  - libuv=1.48.0=hd590300_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h7f98852_2
  - libxml2=2.10.4=hf1b16e4_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - mkl=2023.1.0=h213fc3f_46344
  - ncurses=6.4=h6a678d5_0
  - nettle=3.6=he412f7d_0
  - ninja=1.11.1=h924138e_0
  - openh264=2.1.1=h780b84a_0
  - openssl=3.3.0=h4ab18f5_3
  - pillow=9.3.0=py38hace64e9_1
  - pip=23.3.1=py38h06a4308_0
  - python=3.8.19=h955ad1f_0
  - python_abi=3.8=2_cp38
  - pytorch=1.8.0=py3.8_cuda11.1_cudnn8.0.5_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py38h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tbb=2021.9.0=hf52228f_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.8.0=py38
  - torchvision=0.9.0=py38_cu111
  - typing_extensions=4.11.0=pyha770c72_0
  - wheel=0.41.2=py38h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.4.9=ha95c52a_0
  - pip:
      - absl-py==2.1.0
      - aiohttp==3.9.4
      - aiosignal==1.3.1
      - anyio==4.3.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - argparse==1.4.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.2.0
      - babel==2.14.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - cachetools==5.3.3
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - comm==0.2.2
      - configparser==7.0.0
      - cycler==0.12.1
      - debugpy==1.8.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - docker-pycreds==0.4.0
      - easydict==1.11
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - fastjsonschema==2.19.1
      - filelock==3.13.4
      - fonttools==4.51.0
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - gdown==3.15.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth==2.29.0
      - google-auth-oauthlib==1.0.0
      - googledrivedownloader==0.4
      - gql==0.2.0
      - graphql-core==1.1
      - grpcio==1.62.2
      - h11==0.14.0
      - h5py==3.7.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - hydra-core==0.11.3
      - idna==3.6
      - imageio==2.34.1
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - ipykernel==6.29.4
      - ipython==8.12.3
      - ipywidgets==8.1.2
      - isodate==0.6.1
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.3
      - joblib==1.4.0
      - json5==0.9.24
      - jsonpatch==1.33
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.1
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.13.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.1.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.26.0
      - jupyterlab-widgets==3.0.10
      - kiwisolver==1.4.5
      - knn-cuda==0.2
      - llvmlite==0.33.0
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.5.3
      - matplotlib-inline==0.1.6
      - mistune==3.0.2
      - multidict==6.0.5
      - nbclient==0.10.0
      - nbconvert==7.16.3
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.1
      - notebook==7.1.2
      - notebook-shim==0.2.4
      - numba==0.50.1
      - numpy==1.19.5
      - nvidia-ml-py3==7.352.0
      - oauthlib==3.2.2
      - omegaconf==1.4.1
      - open3d==0.10.0.0
      - opencv-python==4.9.0.80
      - overrides==7.7.0
      - packaging==24.0
      - pandas==1.2.5
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.2.0
      - plyfile==0.7.4
      - pointnet2-ops==3.0.0
      - pointops==1.0
      - pointops2==1.0
      - prometheus-client==0.20.0
      - promise==2.3
      - prompt-toolkit==3.0.43
      - protobuf==3.19.6
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycparser==2.22
      - pygments==2.17.2
      - pyparsing==3.1.2
      - pyransac3d==0.6.0
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - python-louvain==0.16
      - pytorch-metric-learning==0.9.99
      - pytz==2024.1
      - pywavelets==1.4.1
      - pyyaml==6.0
      - pyzmq==25.1.2
      - rdflib==7.0.0
      - referencing==0.34.0
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.18.0
      - rsa==4.9
      - scikit-image==0.16.2
      - scikit-learn==1.3.2
      - scipy==1.7.3
      - send2trash==1.8.3
      - sentry-sdk==1.45.0
      - shortuuid==1.0.13
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.5
      - stack-data==0.6.3
      - subprocess32==3.5.4
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.2
      - termcolor==2.1.0
      - terminado==0.18.1
      - threadpoolctl==3.4.0
      - timm==0.4.5
      - tinycss2==1.2.1
      - tomli==2.0.1
      - torch-cluster==1.5.9
      - torch-geometric==1.7.2
      - torch-points-kernels==0.6.10
      - torch-points3d==1.3.0
      - torch-scatter==2.0.8
      - torch-sparse==0.6.12
      - torch-spline-conv==1.2.1
      - torchnet==0.0.4
      - tornado==6.4
      - tqdm==4.64.1
      - traitlets==5.14.2
      - transforms3d==0.4.1
      - types-python-dateutil==2.9.0.20240316
      - tzdata==2024.1
      - uri-template==1.3.0
      - urllib3==2.2.1
      - visdom==0.2.4
      - wandb==0.8.36
      - watchdog==4.0.0
      - wcwidth==0.2.13
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - werkzeug==3.0.2
      - widgetsnbextension==4.0.10
      - yarl==1.9.4
      - zipp==3.18.1
prefix: /public/xiek/anaconda3/envs/plantmae
